### ISSUE TITLE
Make the return code reflect the global result

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#1]
Hello @Zaid-Ajaj , 

great work and thank you for starting this tool that has been mentioned several times in the past :)

In general, a program return several "status code" which allow the caller to identify the final result. 

So I propose something like:

- `0` -> Everything is fine
- `1` -> Missing `package.json` file [Source](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L120)
- `2` -> Please install the project first [Source](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L126)
- `3` -> One of the dependencies is not correct
    - Missing deps
    - Mismatch version

This is important especially when integrating the tool in a tool chain, this avoid the caller to parser the `stdout text`.

I can send a PR to the repo if the feature is accepted :)

**Comment by Zaid-Ajaj** [comment]
Hello @MangelMaxime, I am glad you like it! 

I agree that the exit result should be correct and not just 0 every time. I think I want to use something like this:
```fs
type AnalysisResult = 
  | EverythingWorks = 0
  | MissingPackageJson = 1
  | NodeModulesNotInstalled = 2
  | LibraryNotInstalled = 3
  | VersionMismatch = 4

let reult = int AnalysisResult.EverythingWorks
result
```

> This is important especially when integrating the tool in a tool chain

Actually we can do even better than just proper exit code ;) I was thinking of having a parameter `--json-output` that returns all the analysis information about missing packages and dependency mismatches etc. 

> can send a PR to the repo if the feature is accepted :)

Absolutely ❤️ PR's are always welcome

**Comment by MangelMaxime** [comment]
We had the same idea about the `enum` :)

And the JSON output is a great idea too I am just not sure yet on how it can be used. I will send a PR to add the `enum`
