### ISSUE TITLE
Prevents crash of the program

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#10]
While working Femto, it happened several time that I run it against an invalid `fsproj` or that I can't restore the project because I don't have the right version of dotnet installed.

In this case, Femto is crashing because I think `ProjectCracker.fullCrack` is throwing an exception that we don't cache. 

I think we should wrap 

```fs
let projectInfo = ProjectCracker.fullCrack project
let libraries = findLibraryWithNpmDeps projectInfo
```

in a `try ... with ...` block. 

Or we could just wrap the entry point with `try .... with ...` and print the `ex.Message` and return `FemtoResult.Crashed` (a new entry to our FemtoResult enum) as a result.

**Comment by Zaid-Ajaj** [comment]
Calls to `ProjectCracker.fullCrack` are now used inside try catch blocks
