### ISSUE TITLE
Support package.{yaml,json5}

### ISSUE THREAD

**Issue by benedictleejh** [Zaid-Ajaj/Femto#104]
pnpm has supported `package.yaml`  and `package.json5` [since 2019](https://github.com/pnpm/pnpm/pull/1799).

It would be nice to support them, especially since not all packages we would need have Fable wrappers, and being able to do stuff like add comments to `package.{yaml,json5}` can help with documentation and organisation for projects with a large number of packages (if they're using pnpm).

**Comment by Zaid-Ajaj** [comment]
Hi there @benedictleejh this feature sounds reasonable to support for sure. Any chance you could give it a try and implement it? I'd be happy to guide and review PRs when necessary

**Comment by benedictleejh** [comment]
Sure, I wouldn't mind giving it a go, though it might take some time to get to it.
