### ISSUE TITLE
If no Femto metadata found don't log as a warning

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#32]
If no metadata found don't log as a warning it can be normal. For example, when checking the transitive dependencies it's normal that some packages don't have them.

It's also "normal" that the user project doesn't have the Femto metadata if it's not a library.

`[16:19:22 WRN] Project Fulma.Elmish does not contain npm dependency metadata`

**Comment by Zaid-Ajaj** [comment]
Isn't this catched by [this check](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L39)?

**Comment by MangelMaxime** [comment]
I was working on the `--validate` case and so the log error comes from [here](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L462)

Before support of the transitive dependencies, it made sense to fail here indeed.

Now we transitive dependencies the question is do we want to fail if the "user" project doesn't have the metadata? My answer would be no because if the "user" project is an aggregation library it makes sense to try to validate it and check that all the npm deps version can be resolved without conflict (that's the case you are working on #21). I am not adding the conflict resolution in my branch when we have it in your branch, we will be able to merge our work.

For example, here is a real world example:

```
Fulma.Elmish --> No Femto metadata
    | Fable.FontAwesome --> No Femto metadata
    | Fable.FontAwesome.Free --> No Femto metadata
    | Fulma.Extensions.Wikiki.Calendar --> Have Femto metadata
        | Fulma --> Have Femto metadata
```

and Femto output this: 

*This is WIP, I still need to work on the wording etc.*

```
[16:47:45 INF] Validating project Fulma.Elmish.fsproj
[16:47:45 INF] Running dotnet restore against the project
[16:47:48 INF] Ensuring project can be analyzed
[16:47:53 WRN] Skipping Fulma.Elmish, because no Femto metadata found
[16:47:53 WRN] Skipping Fable.FontAwesome, because no Femto metadata found
[16:47:53 WRN] Skipping Fable.FontAwesome.Free, because no Femto metadata found
[16:47:53 INF] Fulma.Extensions.Wikiki.Calendar requires npm package bulma-calendar
[16:47:53 INF]   | -- Required range 0.1.7
[16:47:53 INF]   | -- Resolution strategy 'Min'
[16:47:54 INF]   | -- √ Found version 0.1.7 that satisfies the required range
[16:47:54 INF] Fulma requires npm package bulma
[16:47:54 INF]   | -- Required range >= 0.7.2
[16:47:54 INF]   | -- Resolution strategy 'Min'
[16:47:55 INF]   | -- √ Found version 0.7.2 that satisfies the required range
```

So running `femto --validate` against `Fulma.Elmish` will validate that `bulma-calendar` and `bulma` can be installed. Also, we need to run it using `--validate` because is an F# library and so don't have a `package.json` file so we can't use the `--preview` mode.

For info, I am also fixing [that part](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L466-L476) of the algorithm because right now if not version is satisfying it will still return `FemtoResult.ValidationSucceeded`.

**Comment by Zaid-Ajaj** [comment]
> My answer would be no because if the "user" project is an aggregation library it makes sense to try to validate it and check that all the npm deps version can be resolved without conflict

Yes of course! `--validate` should only fail if versions of *required* dependencies cannot be properly resolved
