### ISSUE TITLE
Should we allow passing a directory instead of the full path to the fsproj?

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#34]
`dotnet` command allow the user to path a directory `dotnet restore src` and will find the `project` in the direct directory.

It only complains if there are several `project` files in the directory. Should we mimic this behaviour?

**Comment by Zaid-Ajaj** [comment]
Sounds good to me and the test is simple: 
 - if the given project path is a directory (without an extension) then try find the first file within that directory that has extension `.fsproj`

 - if the given path is a file, check that it has extension `.fsproj`

So the program can be used like this:
```bash
# use working directory directory 
femto

# alias for using working directory with dot
femto .

# use the provided directory
femto ./src 

# use a specific project file
femto ./src/App.fsproj
```
