### ISSUE TITLE
Add --version

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Femto#38]
Adding `--version` to the input arguments.

**Comment by MangelMaxime** [comment]
We can also print the `version` when showing the user manual.

Do you know how we will retrieve the version?

**Comment by Zaid-Ajaj** [comment]
> We can also print the version when showing the user manual

Yeah we could do that but I think it is more common to show the version only when you run `femto --version` like other programs (dotnet, node, npm etc.)

> Do you know how we will retrieve the version?

Ideally it would be a `[<Literal>]` in a file called `Version.fs` and whenever we release a new version, the file is modified by the build script target . . . which we don't have yet 😅 like how Fable does it.

For now I guess just updating the version literal by hand should be enough

**Comment by MangelMaxime** [comment]
It was my idea too :) 

I was curious if their was another solution :)
