### ISSUE TITLE
Unify resolve preview and project analysis logs

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Femto#40]
By @MangelMaxime [in this comment here](https://github.com/Zaid-Ajaj/Femto/pull/39#issuecomment-506288114)

> I asked my self this question in the past and yes they look similar but have small differences.
> --preview will fail is not package.json has been found.
> While --validate can be used even if no package.json is present.
> And --preview show what actions will be applied to the project. It will tell you that it will uninstall that version of the library and install this one.
> However, I do think that running femto without arguments is a duplicate of one of the feature we have.

> I think --preview and running without args should be the same and output the "nicely formatted" logs.

That's what I am thinking of too, not providing any arguments (except project file or path) should be an alias for `--preview` and `--preview` logs can be more nicely formatted

**Comment by MangelMaxime** [comment]
I think we can just support no argument and remove `--preview`.

The log formatting could be handled by #2. 

Like that we go simple for the user.

**Comment by Zaid-Ajaj** [comment]
Yeah I like that, so in summary: 
 - Running `femto` in project directory or by specifying a project will run what we now call `--preview` and logs *what* actions are required for package resolution. 
 - Running `femto --resolve` will execute these actions
 - Explicit `--preview` can be removed
