### ISSUE TITLE
Propose to run run yarn|npm install for the user

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#5]
When detecting that the npm dependencies need to be restored, we could propose to the user to run `yarn install` or `npm install` for him.

This is similar to the behaviour introduce by `webpack@4` where if they don't find `webpack-cli` they propose to run ti for you.

It would give something like that:

```
$ User launch Femto

> Npm packages need to be restored first
> Do you want Femto to run 'npm install' for you? (yes|no) // the command can be 'yarn install' if we detected 'yarn.lock'
> Yes
> Running 'yarn install'

$ Femto retries here
```

**Comment by Zaid-Ajaj** [comment]
Hmm I am not sure, this happens only once, maybe just run the command `yarn install` or `npm install` right away if it hasn't been done before?

**Comment by MangelMaxime** [comment]
Yes, we can run it by default indeed as this command will not delete/change anything that's fine to me.

**Comment by Zaid-Ajaj** [comment]
Femto now runs `npm install` or `yarn install` if it finds `package.json` with no `node_modules`
