### ISSUE TITLE
>= was escaped

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Femto#52]
Just want to let you know that VS seemed to auto-escape `>` in `>=` at one point, causing `>=` to become `&gt;=`. I think it happened when adding another file to the project.

Perhaps `gt`/`gte`/etc. should always be used, never `>`/`>=`/etc.?

**Comment by MangelMaxime** [comment]
Original discussion about the implementation can be found here: https://github.com/Zaid-Ajaj/Femto/issues/7

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @cmeeren for filing the issue, it should now be fixed as of v0.5.2 where the version escaped by Visual Studio will be parsable/compatible by Femto :smile:
```fs
let preprocessVersion (input: string)  =
    input
      .ToLower()
      .Replace("&gt;", ">")
      .Replace("&lt;", "<")
      .Replace("gte", ">=")
      .Replace("gt", ">")
      .Replace("lt", "<")
      .Replace("lte", "<=")
```

**Comment by cmeeren** [comment]
Great! But IMHO something should also be added to the readme. Either a note that it's okay to keep VS's rewrites, or that `gte` etc. should be used to avoid the rewrite.

**Comment by Zaid-Ajaj** [comment]
@cmeeren Done! see README :smile:

**Comment by cmeeren** [comment]
Huzzah! 🎉
