### ISSUE TITLE
Switch from checkmark to V?

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Femto#60]
Is that "V" intended to be a checkmark? Perhaps you could use [an actual checkmark, or an emoji](https://www.alt-codes.net/check-mark-symbols.php)? It would make it more clear, I think.

![image](https://user-images.githubusercontent.com/7766733/68326940-b0eef480-00cc-11ea-8c76-53f2643a03d6.png)

**Comment by Zaid-Ajaj** [comment]
Looks like a check mark to me, not sure why it becomes a V on your machine

![Untitled](https://user-images.githubusercontent.com/13316248/68327293-57d39080-00cd-11ea-9961-b041f32e8ff2.png)

**Comment by cmeeren** [comment]
Strange. In any case, the ✅ checkmark is a lot easier to see. What do you think about using that? And if you have any "X"-es, perhaps use a corresponding icon?

**Comment by Zaid-Ajaj** [comment]
I used the check mark and close icons from Mocha test results because I thought these would usually look the same on very different computers. I don't mind changing it though, PRs are welcome ;)

**Comment by cmeeren** [comment]
I will make a PR for ✔, which has "visual parity" with ❌ if it's needed. Then we can see how that works. In the code it looks very similar, so I'm unsure how it will be in the console.

**Comment by cmeeren** [comment]
Now I just get `?`, both with Cmd and Powershell (standalone or in Windows Terminal Preview).

**Comment by Zaid-Ajaj** [comment]
I guess it has to something to do with your terminal man :/

**Comment by MangelMaxime** [comment]
I think your terminal doesn't support the full range of "Unicode" or something like that.

For example, it was (still is?) one of the arguments for using a terminal emulator like `Cmder` & co.

**Comment by cmeeren** [comment]
Yep. I thought Windows Terminal Preview would support this, but I guess there's more to it than that.

**Comment by cmeeren** [comment]
No, there must be something else going on here. Windows Terminal preview has no problems showing a folder named `✔` using `dir`. Any ideas?

![image](https://user-images.githubusercontent.com/7766733/68457913-c7e33300-0201-11ea-962f-99054af5c205.png)

**Comment by 0x53A** [comment]
you might have to set the output encoding to utf8 in main

**Comment by Zaid-Ajaj** [comment]
@cmeeren Can you please experiment with the advice from @0x53A? I am unable to reproduce and it is a lot of guess work if had to publish a new version with every change for testing. 

To test femt
```
git clone {this repo}
cd Femto
dotnet restore
dotnet run -- ./path/to/YourProject.fsproj
``` 
And you should see the results of your changes

**Comment by cmeeren** [comment]
That worked!

```diff
 [<EntryPoint>]
 let main argv =
+    Console.OutputEncoding <- Text.Encoding.UTF8

     let parser = ArgumentParser.Create<CLIArguments>("femto")
```

**Comment by Zaid-Ajaj** [comment]
Added the patch as of Femto v0.8.3 🚀 @cmeeren can you please take it for a spin?

**Comment by cmeeren** [comment]
Works great, thanks! 👍
