### ISSUE TITLE
Cannot use global paket?

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Femto#65]
Tried to use Femto with the SAFE stack template out of the box and ran into:

> λ femto install Feliz
> [15:04:38 INF] Analyzing project C:\Development\Informedica\apps\GenPed\src\Client\Client.fsproj
> [15:04:38 INF] Running dotnet restore against the project
> [15:04:39 INF] Detected paket.references file -> use paket
> [15:04:39 INF] Installing Feliz within dependency group Client
> [15:04:39 INF] Using locally installed paket
> [15:04:39 ERR] Error while running the following command:
> [15:04:39 ERR] C:\Development\Informedica\apps\GenPed\src\Client> dotnet paket add Feliz --project C:\Development\Informedica\apps\GenPed\src\Client\Client.fsproj --group Client
> [15:04:39 ERR] Process Output:
> [15:04:39 ERR] Process Error: Could not execute because the specified command or file was not found.
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET Core program, but dotnet-paket add Feliz --project C:\Development\Informedica\apps\GenPed\src\Client\Client.fsproj does not exist.
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
> 
>  /c/Development/Informedica/apps/GenPed/src/Client
> λ paket
> Paket version 5.242.1
> 

So, paket is installed as a global tool. When adding paket.exe locally to the .paket folder, it works like a charm.

My local windows 10 dotnet specs:

.NET Core SDK (reflecting any global.json):                                                            
 Version:   3.0.100                                                                                    
 Commit:    04339c3a26                                                                                 
                                                                                                       
Runtime Environment:                                                                                   
 OS Name:     Windows                                                                                  
 OS Version:  10.0.18362                                                                               
 OS Platform: Windows                                                                                  
 RID:         win10-x64                                                                                
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\                                                     
                                                                                                       
Host (useful for support):                                                                             
  Version: 3.0.0                                                                                       
  Commit:  7d57652f33                                                                                  
                                                                                                       
.NET Core SDKs installed:                                                                              
  2.1.801 [C:\Program Files\dotnet\sdk]                                                                
  2.1.802 [C:\Program Files\dotnet\sdk]                                                                
  2.2.401 [C:\Program Files\dotnet\sdk]                                                                
  2.2.402 [C:\Program Files\dotnet\sdk]                                                                
  3.0.100 [C:\Program Files\dotnet\sdk]                                                                
                                                                                                       
.NET Core runtimes installed:                                                                          
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]            
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]            
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]             
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]             
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]            
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]            
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]             
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]             
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]             
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                  
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                  
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                   
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                   
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                   
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Zaid-Ajaj** [comment]
Hello Casper! Femto is able to use the global Paket installation but it detected that there is a *local* paket CLI tool included in the SAFE template.That is why it tried to execute this command:
```
dotnet paket add Feliz --project C:\Development\Informedica\apps\GenPed\src\Client\Client.fsproj --group Client
```
But failed. What version of SAFE template are you using? 

The failure seems to be because the local dotnet tool hasn't been restored first. I don't think you should add a `paket.exe` into your `.paket` directory. Instead, try running a first build using `fake build` and then add Feliz to the project (even though it should work with that first build). 

In any case, I will try to figure out why it isn't working, thanks a lot for filing the issue.

**Comment by Zaid-Ajaj** [comment]
Using latest SAFE template (v1.20) with latest Femto (v0.8.4) works out of the box correctly without any problems. What versions are you using for both SAFE & Femto?

**Comment by halcwb** [comment]
SAFE template version 1.20 as well and femto v 0.8.1. So, is this resolved in 0.8.4?

**Comment by Zaid-Ajaj** [comment]
I can't say for sure, probably best to try it out by  updating your Femto. First uninstall it and then re-install it
```bash
# unintstall
dotnet tool uninstall femto -g 
# re-install
dotnet too install femto -g 
```
you can verify you have the latest version by calling `femto --validate`

**Comment by halcwb** [comment]
So, I tried that but no luck. It still needs a local paket.exe.

**Comment by Zaid-Ajaj** [comment]
Hmm, thanks a lot for trying it out. It is a bit weird thought because the logs say:
```
[15:04:39 INF] Using locally installed paket
```
Which is the result of finding a file in `{repo}/.config/dotnet-tools.json` by the function [isPaketInstalledAsLocalCliTool](https://github.com/Zaid-Ajaj/Femto/blob/master/Program.fs#L909-L923). I will have to debug it further, thanks again

**Comment by halcwb** [comment]
If you want you can have a look on my machine.

**Comment by Zaid-Ajaj** [comment]
I will debug it first locally, I think I know where it went wrong. Safe stack v2 is now WIP and will include local CLI tools anyway so I am fairly confident it will work there OOTB

**Comment by Zaid-Ajaj** [comment]
Hi Casper, is this issue still not resolved for you for latest safe template? I will close the issue for now. Please re-open if the problem persists
