### ISSUE TITLE
Dotnet doesn't seems to escape correctly the XML attributes

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#7]
I think dotnet doesn't escape correctly the XML attributes (or perhaps XML spec don't allow to do what I describe next).

If you use `<` in the version constraint then `dotnet` can't parse the project...

Take the following `fsproj`: 

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Main.fs" />
    </ItemGroup>
    <PropertyGroup>
    <NpmDependencies>
        <NpmPackage Name="date-fns" Version=">= 1.30.0"/>
        <NpmPackage Name="bulma" Version=">= 0.6.0"/>
        <NpmPackage Name="password-generator" Version=">= 1.0.0 < 2.0.0"/>
    </NpmDependencies>
    </PropertyGroup>
</Project>
```

If you run `dotnet restore`, you  get:

```
/Users/maximemangel/Workspaces/Github/Zaid-Ajaj/FemtoTest/NpmPackageNotInstalled/NpmPackageNotInstalled.fsproj(13,65): error MSB4025: The project file could not be loaded. '<', hexadecimal value 0x3C, is an invalid attribute character. Line 13, position 65.
```

This means we can't support all the SemVer syntax...

**Comment by Zaid-Ajaj** [comment]
Omg, this is the last issue I expected to face 😅

I would like to support all possible ranges, a simplifies syntax could help, instead of
```
Version=">= 1.0.0 < 2.0.0"
```
We write
```
Version="And(GTE(1.0.0), LT(2.0.0))"
```
I know maybe not the best, but it should work, leave this one to me

**Comment by MangelMaxime** [comment]
One solution could be to have a specific `Femto` file include in the `package` and read that file like Fable read the `fable` folder.

> Then replace gte with >= and lt with > etc. before parsing as Range

Why not but I would like to support both the standard syntax and this one because hopefully using `<` is not that common... At least, most of us don't do it when lock at the dependencies listed on nuget.

**Comment by Zaid-Ajaj** [comment]
> One solution could be to have a specific Femto file include in the package and read that file like Fable read the fable folder.

I would rather not do this because I would need to look for this file and would need a convention that the file is always sibling to the project and I would need to look for .fable directory which we are not doing at the moment. 

> Why not but I would like to support both the standard syntax and this one

Yeah of course! people would still use things like `>= 1.30.0` but when dotnet complains just change the operators to `gte` and `lt` then replace them back to `>=` when reading the version value

**Comment by MangelMaxime** [comment]
I just remember that `.nuspec` is using `[`, `(`, etc. symbols to represents the version. [Documentation](https://docs.microsoft.com/fr-fr/nuget/reference/package-versioning#version-ranges-and-wildcards)

I suppose they either do that because of legacy heritage or because of the parser being broken.

So the question, is do we want to keep using our own implementation or mimic the behaviour using by Microsoft and Nuget so people can re-use their knowledge?

Either choice is good for me, I just considered that we should consider that option and take a decision.

**Comment by Zaid-Ajaj** [comment]
The use of brackets and parentheses is actually a mathematical notation to represent sets of real numbers, I personally like it but I don't think we need to support multiple notations/syntaxes. If one works fine, it should be enough IMHO

 It can still be added though but we would need to write a parser for it
