### ISSUE TITLE
Cannot specify Nuget package version or --prelease mode

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Zaid-Ajaj/Femto#76]
I was trying to install a package but Nuget complains there's only a prerelease version. I cannot see a way to tell femto to install the prerelease version, nor how to pass a specific version (help says that `--version` is to display femto version).

**Comment by Zaid-Ajaj** [comment]
Hi @alfonsogarciacaro, I believe --version with the install command just fine (last time I checked):

femto install <packageId> --version <version>

**Comment by alfonsogarciacaro** [comment]
Thanks @Zaid-Ajaj! Ah, ok. The help text confused me because `--version [string]` appears before install and that didn't work. Maybe it could be changed?

```
$ femto --help
USAGE: femto [--help] [--validate] [--resolve] [--version [<string>]] [install <package>] [uninstall <package>] [<path>]
```

I just realized that if I install `React.Lit` which has a dependency on `Fable.Lit` and only Fable.Lit includes the `<NpmDependencies>` data, Femto cannot recognize and won't install lit-html. So I need to add `<NpmDependencies>` to all libraries that depend on lit-html, is that correct?

**Comment by Zaid-Ajaj** [comment]
I will check why version option isn't working.

As for the lit-html metadata, it should definitely be recognized as transitive dependency of React.Lit! For example, if you "femto install Feliz.Recharts" it also recognizes the dependencies of react and react-dom from Feliz because Feliz.Recharts depends on Feliz

Can you check that your metadata is correctly written? Inside the directory of your package, do "femto --validate" to see if your npm packages are recognized

**Comment by alfonsogarciacaro** [comment]
The problem seems to be here. Because `apply` is recursive, if `--version` comes before install (as it appears in the help) 
 `PackageArgs` is not `Install` and version is not applied: https://github.com/Zaid-Ajaj/Femto/blob/08f2f60c6262b06895ae867ea48ec02dcbb7e887/src/Program.fs#L1588-L1595

I've sent a PR just to fix the help text :+1:

About the other issue, maybe I did something wrong, let me check again and I'll come back to you 👍

**Comment by alfonsogarciacaro** [comment]
Ok, the help text is fixed and it seems it does install npm dependencies from transitive Nuget dependencies (My mistake! 😅). So we can close this :+1:
