### ISSUE TITLE
Where to find `package.json`?

### ISSUE THREAD

**Issue by philderbeast** [Zaid-Ajaj/Femto#86]
There doesn't seem to be an option to say where to find `package.json`.

```
> dotnet femto --help
USAGE: femto [--help] [--validate] [--resolve] [--version [<string>]] [install <package>] [uninstall <package>] [<path>]

PROJECT:

    <path>                specify the path to the F# project.

OPTIONS:

    --validate            check that the XML tags used in the F# project file are parsable and a npm package version can be calculated.
    --resolve             resolve and install required packages.
    --version [<string>]  display the current version of Femto.
    install <package>     install a package into a project
    uninstall <package>   uninstall a package from the project
    --help                display this list of options.
```

Femto is looking up the directory tree looking for this file.
https://github.com/Zaid-Ajaj/Femto/blob/1bd07d8af31e949c97a364a89a947e28db53ca8a/src/Program.fs#L74-L75

If I need to arrange my source so that this file is in the same directory as my project or in a parent or ancestor directory then can we add a note about that in the readme? Alternately could we take an option saying where to find `package.json`?

I hit this problem trying out the `fable-snowpack` template, https://github.com/fable-compiler/fable-templates/issues/51.

**Comment by MangelMaxime** [comment]
I think the `package.json` file can be at the same level as the fsproj or above.

It is the same behaviour as in JavaScript, your JavaScript files can require modules from the package.json which is the nearest start at the same level and going up. The error you had with the Fable templates is that it has been contributed by the community but not checked/tested enough...
