### ISSUE TITLE
Is Femto an acronyme or a real word?

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Femto#9]
I am wondering is Femto is a real word or if this have a meaning :) Just for curiosity ^^

**Comment by Zaid-Ajaj** [comment]
Femto is the name of a character from my favorite manga called "Berserk" :)

**Comment by MangelMaxime** [comment]
Ok :)

I really need to read this manga :) It's on my list since a long time and now I have one more reason to read it ahah :)

**Comment by Zaid-Ajaj** [comment]
You are missing out on a master piece, my friend :smile:

**Comment by alfonsogarciacaro** [comment]
![image](https://user-images.githubusercontent.com/8275461/61712292-4ea8f880-ad56-11e9-8769-dda9d4d900ae.png)

**Comment by Zaid-Ajaj** [comment]
The feels .... thanks @alfonsogarciacaro 😭
