### ISSUE TITLE
Can't retrieve information

### ISSUE THREAD

**Issue by fourglobe302500** [Zaid-Ajaj/Femto#92]
I was trying to use femto on my fable app but it keeps on emiting this err

`Failed to retrieve information about react required by Fable.React`

What can I do?

**Comment by MangelMaxime** [comment]
It seems like yarn changed its format and Femto cannot parse it.

**Comment by MangelMaxime** [comment]
Hello @fourglobe302500,

someone reported a similar issue to your first problem. Here is my answer with a solution to it.

Note it doesn't explain the error you have in your second message. Do you remember which version of yarn you used?

> Because you don't have a license field in your `package.json` yarn generates a strange response when running `yarn yarn info react versions --json`.
> 
> It returns:
> 
> ```json
> {"type":"warning","data":"package.json: No license field"}
> {"type":"inspect","data":["0.0.0-375616788","0.0.0-00d4f95c2","0.0.0-0203b6567","0.0.0-0935a1db3","0.0.0-0c756fb-697f004","0.0.0-0c756fb-f7f79fd","0.0.0-0cf9fc10b","0.0.0-0e4135e8c","0.0.0-0eea57724","0.0.0-1022ee0ec","0.0.0-10cc40018","0.0.0-11565a207","0.0.0-11b07597e","0.0.0-1214b302e","0.0.0-12adaffef","0.0.0-132b72d7b","0.0.0-172e...}
> ```
> 
> So form now you need to add a license field to your `package.json`.
> 
> If your project is private you can set it to `"license": "UNLICENSED"` [NPM docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license).
> 
> They also recommend setting `"private": true` as an extra security.
>

**Comment by fourglobe302500** [comment]
@MangelMaxime the yarn version is 3.2.1 the latest at the time

**Comment by fourglobe302500** [comment]
at the current time this issue remains since my package.json does have a license

**Comment by MangelMaxime** [comment]
@fourglobe302500 

Yes, the issue in your case now is that the JSON format is not supported. 

Femto was written for yarn 1, so it needs to be updated to support yarn 3 format too.

This is a matter of adapting the decoder here:

https://github.com/Zaid-Ajaj/Femto/blob/f1dd05845ca07dbae8b9df58995a1fb4fa18d940/src/Program.fs#L216

Something like that

```fs
let yarn1Decoder =Decode.field "data" (Decode.list Decode.string
let yarn3Decoder = // todo
let yarnDecoder =
    Decode.oneOf [ yarn1Decoder; yarn3Decoder ]

let versions = Decode.unsafeFromString yarnDecoder  res.Result.Output
```
