### ISSUE TITLE
Little bug in help display

### ISSUE THREAD

**Issue by OkayX6** [Zaid-Ajaj/Femto#95]
Hi :)

**Femto version**: 0.16.0

When running `dotnet femto install --help` we get a few exception errors.

![image](https://user-images.githubusercontent.com/1169339/196408256-8eb5e31e-389f-4a42-bf49-edead086a51a.png)

**Comment by Zaid-Ajaj** [comment]
Hi @OkayX6 unfortunately this is by design of how the `Argu` library works. It doesn't give you `--help` for each argument like `install`
